OCR_DONE = "OCR_DONE"
OCR_EMPTY = "OCR_EMPTY"
BTN_CAPTURE_SHORT = "BTN_CAPTURE_SHORT"
BTN_NEXT_SHORT = "BTN_NEXT_SHORT"
BTN_PREV_SHORT = "BTN_PREV_SHORT"
BTN_NEXT_LONG = "BTN_NEXT_LONG"
BTN_PREV_LONG = "BTN_PREV_LONG
